CREATE TABLE adoptions (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    animal_name VARCHAR(30) NOT NULL,
    adopter_name VARCHAR(30) NOT NULL,
    monthly_fee DECIMAL(10, 2) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);